import type { Locale } from "./types"

const fr = {
  meta: {
    description:
      "Je conçois des plateformes de données et des systèmes d'IA fiables, de l'ingestion au serving LLM : Python, FastAPI, pipelines ETL/ELT, architecture de données, RAG et bases vectorielles.",
    ogDescription:
      "Plateformes de données et systèmes d'IA fiables — Python, Data Architecture, Data Engineering, ETL/ELT, RAG, FastAPI.",
  },
  a11y: {
    skipToContent: "Aller au contenu",
    openMenu: "Ouvrir le menu",
    closeMenu: "Fermer le menu",
    mainNav: "Navigation principale",
    language: "Langue",
    switchTo: "Switch to English",
    metrics: "Chiffres clés",
    social: "Réseaux",
    breadcrumb: "Fil d'Ariane",
  },
  nav: {
    home: "Accueil",
    architecture: "Architecture",
    projects: "Projets",
    skills: "Compétences",
    experience: "Expérience",
    about: "À propos",
    contact: "Contact",
    notes: "Notes",
    github: "Open source",
  },
  cta: {
    contact: "Me contacter",
    featured: "Voir le projet phare",
    downloadCv: "Télécharger le CV",
  },
  palette: {
    title: "Palette de commandes",
    open: "Ouvrir la palette de commandes",
    placeholder: "Rechercher une section, un projet, une action…",
    empty: "Aucun résultat.",
    hint: "↑ ↓ pour naviguer · Entrée pour ouvrir · Échap pour fermer",
    sections: "Sections",
    projects: "Projets",
    actions: "Actions",
    featured: "Projet phare",
    switchLanguage: "Passer le site en anglais",
    downloadCv: "Télécharger le CV (PDF)",
    copyEmail: "Copier l'adresse email",
    emailCopied: "Adresse email copiée",
    copyFailed: "Copie impossible — adresse : ",
    github: "Ouvrir le profil GitHub",
    caseStudy: "Étude de cas",
  },
  status: {
    "in-progress": "En cours",
    completed: "Terminé",
    prototype: "Prototype",
  },
  hero: {
    codeLabel: "Extrait de code : endpoint FastAPI de RAG en streaming",
    codeNote: "Exemple générique : recherche filtrée par tenant, puis réponse du LLM streamée en SSE.",
  },
  focus: {
    eyebrow: "Positionnement",
    title: "Domaines d'expertise",
    description:
      "Un profil Python, data et IA, centré sur la conception de plateformes fiables plutôt que sur des démonstrations isolées.",
  },
  featured: {
    eyebrow: "Projet phare",
    problem: "Problème",
    solution: "Solution",
    highlights: "Points clés",
    role: "Rôle",
    status: "Statut",
    year: "Année",
    stack: "Stack",
  },
  architecture: {
    eyebrow: "Data & AI Architecture",
    title: "Comment je conçois les systèmes",
    description:
      "Deux architectures types, de l'ingestion au serving LLM. Survolez ou parcourez les blocs au clavier pour le détail, puis lisez les décisions et leurs compromis.",
    hint: "Survol ou Tab pour le détail de chaque bloc, Échap pour fermer.",
    decisions: "Décisions d'architecture",
    context: "Contexte",
    decision: "Décision",
    tradeoffs: "Compromis",
    toValidate: "à valider",
  },
  projects: {
    eyebrow: "Projets",
    title: "Projets sélectionnés",
    description:
      "Ce que chaque projet accomplit — problème, solution et rôle — plutôt qu'une simple liste de technologies.",
    featuredBadge: "Phare",
    problem: "Problème",
    solution: "Solution",
    role: "Rôle",
    demo: "Démo",
    caseStudy: "Lire l'étude de cas",
    filterLabel: "Filtrer par technologie",
    all: "Tous",
    count: (n: number) => `${n} projet${n > 1 ? "s" : ""}`,
    empty: "Aucun projet pour ce filtre.",
  },
  caseStudy: {
    back: "Tous les projets",
    toc: "Sur cette page",
    context: "Contexte",
    constraints: "Contraintes",
    architecture: "Architecture",
    dataModel: "Modèle de données",
    decisions: "Décisions & compromis",
    results: "Résultats",
    stack: "Stack",
    nextSteps: "Ce que je ferais ensuite",
    links: "Liens",
    gallery: "Aperçu",
    screenshot: (title: string, i: number) => `${title} — capture ${i}`,
    role: "Rôle",
    team: "Équipe",
    duration: "Durée",
    year: "Année",
    status: "Statut",
    next: "Projet suivant",
    previous: "Projet précédent",
    github: "GitHub",
    demo: "Démo",
    noPublicLinks: "Pas de dépôt public : projet confidentiel ou privé.",
  },
  skills: {
    eyebrow: "Compétences",
    title: "Compétences techniques",
    description:
      "Organisation par domaines d'ingénierie — uniquement les technologies réellement utilisées dans mon parcours.",
    hint: "Survolez ou sélectionnez une compétence pour voir où elle a été utilisée.",
    level: "Niveau",
    levelsLegend: "Échelle de niveau",
    levels: {
      production: { label: "Production", detail: "Utilisé en production" },
      solid: { label: "Solide", detail: "Maîtrisé sur des projets réels" },
      growing: { label: "En montée", detail: "En cours d'approfondissement" },
    },
    usedIn: "Utilisé dans",
    experience: "Expérience",
    project: "Projet",
    noEvidence: "Références à compléter",
    showEvidence: (skill: string) => `${skill} — voir où cette compétence a été utilisée`,
  },
  experience: {
    eyebrow: "Expérience",
    title: "Parcours professionnel",
    description:
      "Rôles, responsabilités et technologies — un fil chronologique centré sur Python, la data et l'ingénierie IA.",
    current: "En cours",
    present: "Aujourd'hui",
    impact: "Impact",
    technologies: "Technologies",
    timeline: "Frise chronologique du parcours",
    viewSkill: (tech: string) => `${tech} — voir la compétence`,
    responsibilities: "Responsabilités",
  },
  engineering: {
    eyebrow: "Méthode",
    title: "De l'idée à la production",
    description: "Une approche système complète : du cadrage métier jusqu'au monitoring, pas seulement un prototype.",
  },
  github: {
    eyebrow: "Open source",
    title: "Open source & GitHub",
    description: "Du code consultable : dépôts publics autour de Python, de la data et de l'IA.",
    source: {
      pinned: "Dépôts épinglés sur GitHub",
      curated: "Sélection de dépôts publics",
      snapshot: "Sélection de dépôts publics",
    },
    profile: "Voir le profil GitHub",
    updated: (date: string) => `Mis à jour ${date}`,
    stars: (n: number) => `${n} étoile${n > 1 ? "s" : ""}`,
    openRepo: (name: string) => `Ouvrir le dépôt ${name} sur GitHub`,
  },
  notes: {
    eyebrow: "Notes",
    title: "Notes techniques",
    description: "Retours d'expérience sur l'architecture data, le RAG et le serving LLM.",
    empty: "Les premières notes sont en cours de rédaction.",
    draft: "Brouillon",
    back: "Toutes les notes",
    readNote: "Lire la note",
    published: (date: string) => `Publié le ${date}`,
  },
  about: {
    eyebrow: "À propos",
    title: "Ingénieur Python, data & IA, orienté production",
    education: "Formation",
    languages: "Langues",
  },
  contact: {
    eyebrow: "Contact",
    title: "Discutons de votre prochaine plateforme data ou IA",
    description: "Une question technique, une mission, ou un besoin d'architecture — écrivez-moi.",
    email: "Email",
    phone: "Téléphone",
    location: "Localisation",
    name: "Nom",
    subject: "Sujet",
    message: "Message",
    namePlaceholder: "Votre nom",
    emailPlaceholder: "votre@email.com",
    subjectPlaceholder: "Sujet de votre message",
    messagePlaceholder: "Contexte, objectif, contraintes techniques...",
    required: "obligatoire",
    send: "Envoyer",
    sending: "Envoi en cours…",
    sentTitle: "Message envoyé",
    sentBody: "Merci. Je vous répondrai dès que possible.",
    sendAnother: "Envoyer un autre message",
    errorGeneric: "Erreur lors de l'envoi du message. Réessayez ou écrivez-moi directement par email.",
    errorNetwork: "Erreur de connexion. Veuillez réessayer.",
  },
  footer: {
    tagline: "Plateformes de données, systèmes IA souverains et architectures prêtes pour la production.",
    rights: "Tous droits réservés.",
  },
  music: {
    play: "Lire coding focus",
    pause: "Pause coding focus",
    preparing: "Préparation…",
    on: "Coding focus · ON",
    off: "▶ Lire coding focus",
    blocked: "Audio bloqué",
  },
  notFound: {
    title: "Page introuvable",
    body: "Cette page n'existe pas ou a été déplacée.",
    back: "Retour à l'accueil",
  },
}

export type Dictionary = typeof fr

const en: Dictionary = {
  meta: {
    description:
      "I design reliable data platforms and AI systems, from ingestion to LLM serving: Python, FastAPI, ETL/ELT pipelines, data architecture, RAG and vector databases.",
    ogDescription:
      "Reliable data platforms and AI systems — Python, Data Architecture, Data Engineering, ETL/ELT, RAG, FastAPI.",
  },
  a11y: {
    skipToContent: "Skip to content",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    mainNav: "Main navigation",
    language: "Language",
    switchTo: "Passer en français",
    metrics: "Key figures",
    social: "Social",
    breadcrumb: "Breadcrumb",
  },
  nav: {
    home: "Home",
    architecture: "Architecture",
    projects: "Projects",
    skills: "Skills",
    experience: "Experience",
    about: "About",
    contact: "Contact",
    notes: "Notes",
    github: "Open source",
  },
  cta: {
    contact: "Get in touch",
    featured: "See the flagship project",
    downloadCv: "Download resume",
  },
  palette: {
    title: "Command palette",
    open: "Open the command palette",
    placeholder: "Search a section, a project, an action…",
    empty: "No results.",
    hint: "↑ ↓ to navigate · Enter to open · Esc to close",
    sections: "Sections",
    projects: "Projects",
    actions: "Actions",
    featured: "Flagship project",
    switchLanguage: "Switch the site to French",
    downloadCv: "Download resume (PDF)",
    copyEmail: "Copy email address",
    emailCopied: "Email address copied",
    copyFailed: "Could not copy — address: ",
    github: "Open GitHub profile",
    caseStudy: "Case study",
  },
  status: {
    "in-progress": "In progress",
    completed: "Completed",
    prototype: "Prototype",
  },
  hero: {
    codeLabel: "Code sample: streaming RAG endpoint with FastAPI",
    codeNote: "Generic example: tenant-filtered retrieval, then the LLM answer streamed over SSE.",
  },
  focus: {
    eyebrow: "Positioning",
    title: "Areas of expertise",
    description:
      "A Python, data and AI profile, focused on designing reliable platforms rather than isolated demos.",
  },
  featured: {
    eyebrow: "Flagship project",
    problem: "Problem",
    solution: "Solution",
    highlights: "Key points",
    role: "Role",
    status: "Status",
    year: "Year",
    stack: "Stack",
  },
  architecture: {
    eyebrow: "Data & AI Architecture",
    title: "How I design systems",
    description:
      "Two reference architectures, from ingestion to LLM serving. Hover or tab through the blocks for details, then read the decisions and their trade-offs.",
    hint: "Hover or Tab for each block's details, Esc to close.",
    decisions: "Architecture decisions",
    context: "Context",
    decision: "Decision",
    tradeoffs: "Trade-offs",
    toValidate: "to validate",
  },
  projects: {
    eyebrow: "Projects",
    title: "Selected projects",
    description: "What each project achieves — problem, solution and role — rather than a plain list of technologies.",
    featuredBadge: "Flagship",
    problem: "Problem",
    solution: "Solution",
    role: "Role",
    demo: "Demo",
    caseStudy: "Read the case study",
    filterLabel: "Filter by technology",
    all: "All",
    count: (n: number) => `${n} project${n > 1 ? "s" : ""}`,
    empty: "No project matches this filter.",
  },
  caseStudy: {
    back: "All projects",
    toc: "On this page",
    context: "Context",
    constraints: "Constraints",
    architecture: "Architecture",
    dataModel: "Data model",
    decisions: "Decisions & trade-offs",
    results: "Results",
    stack: "Stack",
    nextSteps: "What I would do next",
    links: "Links",
    gallery: "Preview",
    screenshot: (title: string, i: number) => `${title} — screenshot ${i}`,
    role: "Role",
    team: "Team",
    duration: "Duration",
    year: "Year",
    status: "Status",
    next: "Next project",
    previous: "Previous project",
    github: "GitHub",
    demo: "Demo",
    noPublicLinks: "No public repository: confidential or private project.",
  },
  skills: {
    eyebrow: "Skills",
    title: "Technical skills",
    description: "Organised by engineering domain — only technologies I have actually used in my career.",
    hint: "Hover or select a skill to see where it was used.",
    level: "Level",
    levelsLegend: "Level scale",
    levels: {
      production: { label: "Production", detail: "Used in production" },
      solid: { label: "Solid", detail: "Proficient on real projects" },
      growing: { label: "Growing", detail: "Currently deepening" },
    },
    usedIn: "Used in",
    experience: "Experience",
    project: "Project",
    noEvidence: "References to be added",
    showEvidence: (skill: string) => `${skill} — see where this skill was used`,
  },
  experience: {
    eyebrow: "Experience",
    title: "Professional background",
    description: "Roles, responsibilities and technologies — a timeline focused on Python, data and AI engineering.",
    current: "Current",
    present: "Present",
    impact: "Impact",
    technologies: "Technologies",
    timeline: "Career timeline",
    viewSkill: (tech: string) => `${tech} — view skill`,
    responsibilities: "Responsibilities",
  },
  engineering: {
    eyebrow: "Method",
    title: "From idea to production",
    description: "An end-to-end system approach: from business framing to monitoring, not just a prototype.",
  },
  github: {
    eyebrow: "Open source",
    title: "Open source & GitHub",
    description: "Code you can read: public repositories around Python, data and AI.",
    source: {
      pinned: "Pinned repositories on GitHub",
      curated: "Selection of public repositories",
      snapshot: "Selection of public repositories",
    },
    profile: "View GitHub profile",
    updated: (date: string) => `Updated ${date}`,
    stars: (n: number) => `${n} star${n > 1 ? "s" : ""}`,
    openRepo: (name: string) => `Open the ${name} repository on GitHub`,
  },
  notes: {
    eyebrow: "Notes",
    title: "Technical notes",
    description: "Field notes on data architecture, RAG and LLM serving.",
    empty: "The first notes are being written.",
    draft: "Draft",
    back: "All notes",
    readNote: "Read the note",
    published: (date: string) => `Published on ${date}`,
  },
  about: {
    eyebrow: "About",
    title: "Python, data & AI engineer, production-minded",
    education: "Education",
    languages: "Languages",
  },
  contact: {
    eyebrow: "Contact",
    title: "Let's talk about your next data or AI platform",
    description: "A technical question, a project, or an architecture need — write to me.",
    email: "Email",
    phone: "Phone",
    location: "Location",
    name: "Name",
    subject: "Subject",
    message: "Message",
    namePlaceholder: "Your name",
    emailPlaceholder: "you@email.com",
    subjectPlaceholder: "Subject of your message",
    messagePlaceholder: "Context, goal, technical constraints...",
    required: "required",
    send: "Send",
    sending: "Sending…",
    sentTitle: "Message sent",
    sentBody: "Thank you. I will get back to you as soon as possible.",
    sendAnother: "Send another message",
    errorGeneric: "The message could not be sent. Please try again or email me directly.",
    errorNetwork: "Connection error. Please try again.",
  },
  footer: {
    tagline: "Data platforms, sovereign AI systems and production-ready architectures.",
    rights: "All rights reserved.",
  },
  music: {
    play: "Play coding focus music",
    pause: "Pause coding focus music",
    preparing: "Preparing…",
    on: "Coding focus · ON",
    off: "▶ Play coding focus",
    blocked: "Audio blocked",
  },
  notFound: {
    title: "Page not found",
    body: "This page does not exist or has been moved.",
    back: "Back to home",
  },
}

const dictionaries: Record<Locale, Dictionary> = { fr, en }

export function getDictionary(locale: Locale): Dictionary {
  return dictionaries[locale]
}
